(define (yatch-girls)
	(let 	((mr-moore-daughter (amb 'lorna 'melissa 'rosalind 'gabrielle 'mary-ann))
		(mr-moore-yatch (amb 'lorna 'melissa 'rosalind 'gabrielle 'mary-ann)))
		(require (eq? mr-moore-yatch lorna))
		(require (eq? mr-moore-daughter 'mary-ann))
		(let 	((colonel-downing-daughter (amb 'lorna 'melissa 'rosalind 'gabrielle 'mary-ann))
			(colonel-downing-yatch (amb 'lorna 'melissa 'rosalind 'gabrielle 'mary-ann)))
			(require (eq? colonel-downing-yatch 'melissa))
			(require (not (eq? colonel-downing-daughter colonel-downing-yatch)))
			(let 	((mr-hall-daughter (amb 'lorna 'melissa 'rosalind 'gabrielle 'mary-ann))
				(mr-hall-yatch (amb 'lorna 'melissa 'rosalind 'gabrielle 'mary-ann)))
				(require (eq? mr-hall-yatch 'rosalind))
				(require (not (eq? mr-hall-daughter mr-hall-yatch)))
				(let 	((sir-barnacle-daughter (amb 'lorna 'melissa 'rosalind 'gabrielle 'mary-ann))
					(sir-barnacle-yatch (amb 'lorna 'melissa 'rosalind 'gabrielle 'mary-ann)))
					(require (eq? sir-bernard-yatch 'gabrielle))
					(require (eq? sir-bernard-daughter 'melissa))
					(let 	((dr-parker-daughter (amb 'lorna 'melissa 'rosalind 'gabrielle 'mary-ann))
						(dr-parker-yatch (amb 'lorna 'melissa 'rosalind 'gabrielle 'mary-ann)))
						(require (eq? dr-parker-yatch 'mary-ann))
						(require (eq? dr-parker-daughter (daughter-father-yatch mr-moore-daughter mr-moore-yatch colonel-downing-daughter colonel-downing-yatch mr-hall-daughter mr-hall-yatch sir-barnacle-daughter sir-barnacle-yatch 'gabrielle)))
						(list 	(list 'mr-moore-daughter mr-moore-daughter)
							(list 'colonel-downing-daughter colonel-downing-daughter)
							(list 'mr-hall-daughter mr-hall-daughter)
							(list 'sir-barnacle-daughter sir-barnacle-daughter)
							(list 'dr-parker-daughter dr-parker-daughter))))))))					
	

(define (daughter-father-yatch f1 y1 f2 y2 f3 y3 f4 y4 daughter-name)
	(if (eq? f1 daughter-name) y1)
	(if (eq? f2 daughter-name) y2)
	(if (eq? f3 daughter-name) y3)
	(if (eq? f4 daughter-name) y4 "No father found for this daughter"))
